version: '3.9'
services:
  db:
    image: kartoza/postgis:14-3.2
    ports: 
      - "25432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db

volumes:
  postgis-data:

