version: '3.9'
services:
  db:
    container_name: "db"
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_search

volumes:
  db:

